### ISSUE TITLE
你好 我想请问一下,怎么添加一个不在menu菜单上展示的子路由 

### ISSUE THREAD

**Issue by Jiong-Sen** [NLRX-WJC/react-antd-admin-template#19]
比如一个table中的一列 我点击查看详情 跳转到一个子路由, 但是这个子路由不需要在菜单中显示

**Comment by NLRX-WJC** [comment]
目前代码里应该没有加，但是你可以在路由配置文件里给路由加一个hidden属性，然后再  https://github.com/NLRX-WJC/react-antd-admin-template/blob/master/src/views/layout/Sider/Menu/index.jsx#L27 这里添加一下对hidden的判断，过滤掉hidden为true的路由即可

**Comment by Jiong-Sen** [comment]
好的 谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NLRX-WJC/react-antd-admin-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NLRX-WJC/react-antd-admin-template] 你好 我想请问一下,怎么添加一个不在menu菜单上展示的子路由  (#19)





 
目前代码里应该没有加，但是你可以在路由配置文件里给路由加一个hidden属性，然后再  https://github.com/NLRX-WJC/react-antd-admin-template/blob/master/src/views/layout/Sider/Menu/index.jsx#L27 这里添加一下对hidden的判断，过滤掉hidden为true的路由即可
