### ISSUE TITLE
打包部署服务器一片空白？

### ISSUE THREAD

**Issue by lxy910812** [NLRX-WJC/react-antd-admin-template#6]
什么情况

**Comment by NLRX-WJC** [comment]
在 `config-overrides.js` 文件里把 `publicPath` 改成你的哦，或者你将以下代码注释：
```js

const addCustomize = () => (config) => {
  //if (config.output.publicPath) {
  //  config.output.publicPath =
  //    process.env.NODE_ENV === "production"
  //      ? "/react-antd-admin-template/"
  //      : "/";
  //}
  if (config.resolve) {
    config.resolve.extensions.push(".jsx");
  }
  return config;
};
```

还有在 `.env.production` 文件中 将 `PUBLIC_URL` 改为你的，或者将这行代码直接删除

**Comment by lxy910812** [comment]
> 在`config-overrides.js`文件里把`publicPath`改成你的哦，或者你将以下代码注释：
> 
> ```js
> const  addCustomize  =  （） =>  （config ） =>  { 
>   //如果（config.output.publicPath）{ 
>   // config.output.publicPath = 
>   // process.env.NODE_ENV ===“ production” 
>   //吗？“ / react-antd-admin-template /” 
>   //：“ /”; 
>   //} 
>   如果 （配置。解决） { 
>     配置。解决。扩展名。push （“ .jsx” ）; 
>   } 
>   return  config ; 
> } ;
> ```
> 
> 还有在`.env.production`文件`PUBLIC_URL`中将改变你的，或者将这行代码直接删除

可以了，谢谢作者，你这个就比较简单，像AntdPro那个就太多东西了，太复杂了，看不懂，25k，star那个，完全看不懂
