### ISSUE TITLE
请问这个项目是基于create-react-app创建的么，是如何启用less的呢，感谢

### ISSUE THREAD

**Issue by dlscodes** [NLRX-WJC/react-antd-admin-template#7]

**Comment by NLRX-WJC** [comment]
是的，启用 `less` 的话是用了 `antd` 官方推荐的方式，具体可以查看这里https://3x.ant.design/docs/react/use-with-create-react-app-cn#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98

**Comment by dlscodes** [comment]
@NLRX-WJC 感谢热心解答，最近从这个项目中学到了很多，感谢感谢
