### ISSUE TITLE
系统设置有个问题

### ISSUE THREAD

**Issue by lxy910812** [NLRX-WJC/react-antd-admin-template#8]
固定header那里第一次有效果，后面几次都是没有效果的，无论是刷新还是从新打开网页，

**Comment by NLRX-WJC** [comment]
那个系统设置不是说在页面上设置好以后就一劳永逸了，那个功能的初衷不是给用户使用的，是给开发者使用的，放你确定好你的设置后，需要点击拷贝设置按钮，然后将拷贝好的内容替换代码里的settins文件，这样下一次就生效了，那个系统设置面板只是提供个设置预览作用，刷新后当然就没用了，要想永久生效就需要替换settings文件了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lxy910812 <notifications@github.com&gt;
发送时间: 2020年6月10日 14:23
收件人: NLRX-WJC/react-antd-admin-template <react-antd-admin-template@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[NLRX-WJC/react-antd-admin-template] 系统设置有个问题 (#8)





 
固定header那里第一次有效果，后面几次都是没有效果的，无论是刷新还是从新打开网页，

**Comment by lxy910812** [comment]
> 老兄，连个star也不点么，好心塞啊😭

点了，你的antd，跟axios版本怎么这么低啊？

**Comment by NLRX-WJC** [comment]
> > 老兄，连个star也不点么，好心塞啊😭
> 
> 点了，你的antd，跟axios版本怎么这么低啊？

what?? axios版本低？axios最高版本现在是多少？
antd当时选择3.x版本是为了兼容更低的浏览器，因为4.x版本放弃兼容了一些浏览器，后面会考虑升级antd版本
